version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day-of-week: "monday"
      timezone: "Etc/UTC"
      time: "03:00"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day-of-week: "monday"
      timezone: "Etc/UTC"
      time: "03:00"
    target-branch: "develop"
