version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    assignees:
      - "calteran"
    groups:
      crate-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "main"
    assignees:
      - "calteran"
    groups:
      actions-deps:
        patterns:
          - "*"
