[package]
name = "oliframe"
description = "Add a border to one or more images (quickly)"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
csscolorparser = "0.6.2"
image = "0.24.7"
junk_file = "0.1.1"
rayon = "1.8.0"
