[package]
name = "qwikborder"
description = "Add a border to one or more images (quickly)"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
crossterm = "0.27.0"
image = "0.24.7"
indicatif = { version = "0.17.7", features = ["rayon"] }
rayon = "1.8.0"
