[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
]

[bans]
skip = [
    "thiserror@1.0.69",
    #└── rav1e v0.7.1 <- fixed in `master`, but no release yet
    #    └── ravif v0.11.11
    #        └── image v0.25.5
    #            └── oliframe v0.2.4
    "thiserror-impl@1.0.69"
    #└── thiserror v1.0.69
    #    └── rav1e v0.7.1 <- fixed in `master`, but no release yet
    #        └── ravif v0.11.11
    #            └── image v0.25.5
    #                └── oliframe v0.2.4
]