[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0",
]

[bans]
skip = [
    "thiserror@1.0.69", # Until https://github.com/xiph/rav1e/pull/3403 (image dep)
    "thiserror-impl@1.0.69" # Until https://github.com/xiph/rav1e/pull/3403 (image dep)
]