name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure toolchain
        run: rustup toolchain install stable --profile minimal
      - name: install machete
        run: cargo install cargo-machete
      - name: run machete
        run: cargo machete
      - name: format
        run: cargo fmt --all -- --check
      - name: build
        run: cargo build
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: test
        run: cargo test
      - name: docs
        run: cargo doc --no-deps