#file: noinspection SpellCheckingInspection
name: CI

on:
  pull_request:
    branches-ignore:
      - 'release-plz*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure toolchain
        run: rustup toolchain install stable --profile minimal
      - name: build
        run: cargo build
      - name: test
        run: cargo test
      - name: docs
        run: cargo doc --no-deps
  coverage:
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: generate coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --workspace --timeout 120 --out xml
      - name: upload coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
  enforce-clean-code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: configure toolchain
        run: rustup toolchain install stable --profile minimal
      - name: run deny
        uses: EmbarkStudios/cargo-deny-action@v2
      - name: run machete
        uses: bnjbvr/cargo-machete@main
      - name: format
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings